FROM openjdk:8
WORKDIR /app
ADD target/RabbitmqIntegration-0.0.1-SNAPSHOT.jar /app/RabbitmqIntegration-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","RabbitmqIntegration-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080