FROM openjdk:8
WORKDIR /app
ADD target/PostgresDbIntegration-0.0.1-SNAPSHOT.jar /app/PostgresDbIntegration-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","PostgresDbIntegration-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080